-- Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2022-11-22 17:31:07 EET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
DROP TABLE IF EXISTS contracte;
DROP TABLE IF EXISTS detalii_concedii;
DROP TABLE IF EXISTS concedii;
DROP TABLE IF EXISTS detalii_contributii;
DROP TABLE IF EXISTS detalii_retineri;
DROP TABLE IF EXISTS detalii_sporuri;
DROP TABLE IF EXISTS functii;
DROP TABLE IF EXISTS pontaje;
DROP TABLE IF EXISTS retineri;
DROP TABLE IF EXISTS sporuri;
DROP TABLE IF EXISTS contributii;
DROP TABLE IF EXISTS departamente;
DROP TABLE IF EXISTS angajati;

CREATE TABLE angajati (
    marca     CHAR(10) NOT NULL,
    nume      CHAR(20),
    prenume   CHAR(20),
    cnp       NUMERIC(13),
    email  CHAR(40),
    adresa    CHAR(100),
    telefon   NUMERIC(10)
);

ALTER TABLE angajati ADD CONSTRAINT marca_pk PRIMARY KEY ( marca );

CREATE TABLE concedii (
    cod_concedii  CHAR(20) NOT NULL,
    tip_concedii  CHAR(60)
);

ALTER TABLE concedii ADD CONSTRAINT concedii_pk PRIMARY KEY ( cod_concedii );

CREATE TABLE contracte (
    cod_contract    CHAR(20) NOT NULL,
    tip_contract    CHAR(50),
    Nr_contract  CHAR(20),
    salarii         NUMERIC(20, 2),
    data_contract   DATE,
    data_incepere   DATE,
    data_sfarsire   DATE,
    marca           VARCHAR(10) NOT NULL
);

ALTER TABLE contracte ADD CONSTRAINT contracte_pk PRIMARY KEY ( cod_contract,
                                                                marca );

CREATE TABLE contributii (
    cod_contributii  CHAR(10) NOT NULL,
    denumire         CHAR(30),
    procent          decimal
);

ALTER TABLE contributii ADD CONSTRAINT contributii_pk PRIMARY KEY ( cod_contributii );

CREATE TABLE departamente (
    cod_departament       CHAR(10) NOT NULL,
    denumire_departament  CHAR(40)
);

ALTER TABLE departamente ADD CONSTRAINT departamente_pk PRIMARY KEY ( cod_departament );

CREATE TABLE detalii_concedii (
    data_inceperii   DATE,
    data_incheiere   DATE,
    data_solicitare  DATE,
    marca            VARCHAR(10) NOT NULL,
    cod_concedii     CHAR(20) NOT NULL
);

ALTER TABLE detalii_concedii ADD CONSTRAINT detalii_concedii_pk PRIMARY KEY ( marca,
                                                                              cod_concedii );

CREATE TABLE detalii_contributii (
    marca            VARCHAR(10) NOT NULL,
    cod_contributii  CHAR(10) NOT NULL,
    data             CHAR(15) NOT NULL,
    valoare          NUMERIC(15, 2)
);

ALTER TABLE detalii_contributii
    ADD CONSTRAINT detalii_contributii_pk PRIMARY KEY ( data,
                                                        cod_contributii,
                                                        marca );

CREATE TABLE detalii_retineri (
    data          CHAR(15) NOT NULL,
    valoare       NUMERIC(15, 2),
    marca         VARCHAR(10) NOT NULL,
    cod_retinere  CHAR(15) NOT NULL
);

ALTER TABLE detalii_retineri
    ADD CONSTRAINT detalii_retineri_pk PRIMARY KEY ( data,
                                                     cod_retinere,
                                                     marca );

CREATE TABLE detalii_sporuri (
    data      CHAR(15) NOT NULL,
    valoare   NUMERIC(15, 2),
    marca     VARCHAR(10) NOT NULL,
    cod_spor  CHAR(15) NOT NULL
);

ALTER TABLE detalii_sporuri
    ADD CONSTRAINT detalii_sporuri_pk PRIMARY KEY ( data,
                                                    marca,
                                                    cod_spor );

CREATE TABLE functii (
    cod_functie       CHAR(20) NOT NULL,
    denumire_functie  CHAR(40),
    cod_departament   CHAR(10) NOT NULL,
    marca             VARCHAR(10) NOT NULL
);

ALTER TABLE functii
    ADD CONSTRAINT functii_pk PRIMARY KEY ( cod_functie,
                                            marca,
                                            cod_departament );

CREATE TABLE pontaje (
    cod_pontaj        CHAR(20) NOT NULL,
    data              DATE NOT NULL,
    marca             VARCHAR(10) NOT NULL,
    cod_concedii      CHAR(20) NOT NULL,
    total_ore         numeric(3),
    ore_lucrate       numeric(5),
    ore_suplimentare  numeric(5),
    ore_invoire       numeric(5),
    ore_it            numeric(5)
);

ALTER TABLE pontaje
    ADD CONSTRAINT pontaje_pk PRIMARY KEY ( cod_pontaj,
                                            data,
                                            marca,
                                            cod_concedii );

CREATE TABLE retineri (
    cod_retinere  CHAR(15) NOT NULL,
    denumire      CHAR(100),
    procent       decimal
);

ALTER TABLE retineri ADD CONSTRAINT retineri_pk PRIMARY KEY ( cod_retinere );

CREATE TABLE sporuri (
    cod_spor  CHAR(15) NOT NULL,
    tip_spor  CHAR(100),
    procent   decimal
);

ALTER TABLE sporuri ADD CONSTRAINT sporuri_pk PRIMARY KEY ( cod_spor );

ALTER TABLE contracte
    ADD CONSTRAINT contracte_angajați_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );

ALTER TABLE detalii_concedii
    ADD CONSTRAINT detalii_concedii_angajați_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );

ALTER TABLE detalii_concedii
    ADD CONSTRAINT detalii_concedii_concedii_fk FOREIGN KEY ( cod_concedii )
        REFERENCES concedii ( cod_concedii );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE detalii_contributii
    ADD CONSTRAINT detalii_contributii_contributii_fk FOREIGN KEY ( cod_contributii )
        REFERENCES contributii ( cod_contributii );

ALTER TABLE detalii_retineri
    ADD CONSTRAINT detalii_retineri_angajați_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );

ALTER TABLE detalii_retineri
    ADD CONSTRAINT detalii_retineri_retineri_fk FOREIGN KEY ( cod_retinere )
        REFERENCES retineri ( cod_retinere );

ALTER TABLE detalii_sporuri
    ADD CONSTRAINT detalii_sporuri_angajați_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );

ALTER TABLE detalii_sporuri
    ADD CONSTRAINT detalii_sporuri_sporuri_fk FOREIGN KEY ( cod_spor )
        REFERENCES sporuri ( cod_spor );

ALTER TABLE functii
    ADD CONSTRAINT functii_angajati_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );

ALTER TABLE functii
    ADD CONSTRAINT functii_departamente_fk FOREIGN KEY ( cod_departament )
        REFERENCES departamente ( cod_departament );

ALTER TABLE detalii_contributii
    ADD CONSTRAINT marca_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );

ALTER TABLE pontaje
    ADD CONSTRAINT pontaje_angajați_fk FOREIGN KEY ( marca )
        REFERENCES angajati ( marca );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
